# NumPy Matrix + Pandas Assignment

## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

In [31]:
import pandas as pd
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```

In [32]:
print(matrix*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```

In [33]:
matrix
print(matrix.sum(axis = 1))

[ 6 15 24]

## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```

In [34]:
matrix
print(matrix.sum(axis = 0))

[12 15 18]

## Q5. Extract Second Row

### Output
```python
[4 5 6]
```

In [35]:
matrix
print(matrix[1,:])

[4 5 6]

## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |

In [38]:
df = pd.DataFrame({
    'Name' : ['Raj', 'Amit', 'Neha', 'Priya'],
    'Marks': [80,70,90,85]
})
df

    Name  Marks
0    Raj     80
1   Amit     70
2   Neha     90
3  Priya     85

## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```

In [46]:
df = pd.DataFrame({
    'Name' : ['Raj', 'Amit', 'Neha', 'Priya'],
    'Marks': [80,70,90,85],
})
df['Bonus'] = df['Marks'] + 5
print(df)

    Name  Marks  Bonus
0    Raj     80     85
1   Amit     70     75
2   Neha     90     95
3  Priya     85     90

## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```

In [61]:
df = pd.DataFrame({
    'Name' : ['Raj', 'Amit', 'Neha', 'Priya'],
    'Marks': [80,70,90,85],
})

print(df.query("Marks > 80"))

    Name  Marks
2   Neha     90
3  Priya     85

## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```

In [63]:
df
print(df.iloc[0,:])

Name     Raj
Marks     80
Name: 0, dtype: object

## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```

In [65]:
print(df.iloc[2,:])

Name     Neha
Marks      90
Name: 2, dtype: object

## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```

In [66]:
df
print(df.iloc[0:2,:])

   Name  Marks
0   Raj     80
1  Amit     70

## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```

In [68]:
print(df.iloc[:, 0])

0      Raj
1     Amit
2     Neha
3    Priya
Name: Name, dtype: object

## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```

In [73]:
df
df.loc[1, 'Marks'] = 75
df

    Name  Marks
0    Raj     80
1   Amit     75
2   Neha     90
3  Priya     85

## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```

In [78]:
df
df.sort_values(by='Marks', ascending=False, inplace=True)
print(df)

    Name  Marks
2   Neha     90
3  Priya     85
0    Raj     80
1   Amit     75