
# Pandas Class 6 Assignment

## Level: Basic to Intermediate

### Instructions
- Solve all questions using Pandas.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display Unique Values

## Problem Statement
Create a DataFrame with a City column and display all unique cities.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
['Bhopal' 'Indore' 'Delhi']
```

In [55]:
import pandas as pd
df = pd.DataFrame({
    'City':['Bhopal','Indore','Bhopal','Delhi']
})
df
print(df.City.unique())

['Bhopal' 'Indore' 'Delhi']


# Q2. Count Unique Values

## Problem Statement
Find the number of unique cities in a DataFrame.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
3
```

In [56]:
df
print(df.City.nunique())

3


# Q3. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
Bhopal    2
Indore    1
Delhi     1
```

In [57]:
df
print(df.City.value_counts())

City
Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64


# Q4. Group By City

## Problem Statement
Find average marks city-wise using groupby().

## Sample Input
```python
City   Marks
Bhopal 80
Bhopal 90
Delhi  70
```

## Sample Output
```python
Bhopal 85
Delhi  70
```

In [58]:
df = pd.DataFrame({
    'City':['Bhopal','Delhi','Bhopal'],
    'Marks':[80,70,90]
})
df
print(df.groupby('City')['Marks'].mean())

City
Bhopal    85.0
Delhi     70.0
Name: Marks, dtype: float64


# Q5. Sort Values

## Problem Statement
Sort students by Marks in ascending order.

## Sample Output
```python
Sorted DataFrame
```

In [59]:
df = pd.DataFrame({
    'Name':['Rahul','Riya','Priya','Siya','Ziya'],
    'Marks':[60,90,70,55,80]
})
df
df.sort_values(by='Marks')

    Name  Marks
3   Siya     55
0  Rahul     60
2  Priya     70
4   Ziya     80
1   Riya     90


# Q6. Sort Values Descending

## Problem Statement
Sort students by Marks in descending order.

## Sample Output
```python
Sorted DataFrame
```

In [60]:
df
df.sort_values(by='Marks',ascending=False)

    Name  Marks
1   Riya     90
4   Ziya     80
2  Priya     70
0  Rahul     60
3   Siya     55


# Q7. Filter Records

## Problem Statement
Display students having marks greater than 75.

## Sample Output
```python
Filtered rows
```

In [61]:
print(df[df.Marks > 70])

   Name  Marks
1  Riya     90
4  Ziya     80


# Q8. Multiple Conditions

## Problem Statement
Display students whose marks are greater than 70 and age is greater than 20.

## Sample Output
```python
Filtered rows
```

In [62]:
df = pd.DataFrame({
    'Name':['Rahul','Riya','Priya','Siya','Ziya'],
    'Marks':[60,90,70,55,80],
    'Age':[27,30,19,20,18]
})
df
print(df[(df.Marks > 70) & (df.Age > 20)])

   Name  Marks  Age
1  Riya     90   30


# Q9. Group By Department

## Problem Statement
Create Employee and Department data and find total salary department-wise.

## Sample Output
```python
HR       50000
IT      120000
```

In [63]:
data = {
    "Employee": ["Mitchell", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "HR", "IT", "HR", "IT", "IT", "HR"],
    "Salary": [20000, 40000, 15000, 35000, 15000, 45000, 0, 0] 
}

df = pd.DataFrame(data)

# 2. Group by 'Department' and find the total sum of 'Salary'
result = df.groupby("Department")["Salary"].sum()

# 3. Display the final output
print(result)

Department
HR     50000
IT    120000
Name: Salary, dtype: int64


# Q10. Complete Practice Question

## Problem Statement
Create a DataFrame containing:
- Name
- Age
- City
- Marks

Perform:
1. Show unique cities
2. Count city frequency
3. Filter marks > 80
4. Sort by marks

## Sample Output
```python
Required Results
```

In [64]:
df = pd.DataFrame({
    'Name':['Rahul','Riya','Priya','Siya','Ziya'],
    'Age':[27,30,19,20,18],
    'City':['Bhopal','Maihar','Bhopal','Maihar','Rewa'],
    'Marks':[60,90,70,55,80]
})
df
print(df.City.unique())
print(df.City.value_counts())
print(df[df.Marks > 80])
print(df.sort_values(by='Marks'))

['Bhopal' 'Maihar' 'Rewa']
City
Bhopal    2
Maihar    2
Rewa      1
Name: count, dtype: int64
   Name  Age    City  Marks
1  Riya   30  Maihar     90
    Name  Age    City  Marks
3   Siya   20  Maihar     55
0  Rahul   27  Bhopal     60
2  Priya   19  Bhopal     70
4   Ziya   18    Rewa     80
1   Riya   30  Maihar     90