# Pandas Class 5 Assignment

## Topics
- sort_values()
- mean()
- median()
- mode()
- value_counts()
- corr()
- cov()

Difficulty: Easy to Moderate

## Q1. Sort Age in Ascending Order

Input:
Age = [25, 18, 30, 22]

Output:
18
22
25
30

In [60]:
import pandas as pd

df = pd.DataFrame({
    'Age':[25,18,30,22]
})
df
df.sort_values(by='Age')

   Age
1   18
3   22
0   25
2   30

## Q2. Sort Marks in Descending Order

Input:
Marks = [70, 95, 80, 60]

Output:
95
80
70
60

In [61]:
df = pd.DataFrame({
    'Marks':[70,95,80,60]
})
df
df.sort_values(by='Marks', ascending=False)

   Marks
1     95
2     80
0     70
3     60

## Q3. Find Mean Age

Input:
Age = [20, 25, 30, 25]

Output:
25.0

In [62]:
df = pd.DataFrame({
    'Age':[20,15,30,25]
})
df
df.mean(numeric_only=True)

Age    22.5
dtype: float64

## Q4. Find Median Marks

Input:
Marks = [50, 60, 70, 80, 90]

Output:
70

In [63]:
df = pd.DataFrame({
    'Marks':[50,60,70,80,90]
})
df
df.median(numeric_only=True)

Marks    70.0
dtype: float64

## Q5. Find Mode

Input:
Age = [20, 25, 25, 30, 25]

Output:
25

In [64]:
df = pd.DataFrame({
    'Age':[20,25,25,30,25]
})
df
df.mode()

   Age
0   25

## Q6. Find Maximum Score

Input:
Score = [78, 90, 67, 88]

Output:
90

In [65]:
df = pd.DataFrame({
    'Score':[78,90,67,88]
})
df
df.Score.max()

90

## Q7. Find Minimum Score

Input:
Score = [78, 90, 67, 88]

Output:
67

In [66]:
df.Score.min()

67

## Q8. Count City Frequency

Input:
City = ['Bhopal','Indore','Bhopal','Jabalpur']

Output:
Bhopal      2
Indore      1
Jabalpur    1

In [67]:
df = pd.DataFrame({
    'City':['Bhopal','Indore','Bhopal','Jabalpur']
})
df
df.City.value_counts()

City
Bhopal      2
Indore      1
Jabalpur    1
Name: count, dtype: int64

## Q9. Find Percentage Frequency

Input:
City = ['A','A','B','C']

Output:
A = 50%
B = 25%
C = 25%

In [68]:
df = pd.DataFrame({
    'City':['A','A','B','C']
})
df
df.City.value_counts(normalize=True)*100

City
A    50.0
B    25.0
C    25.0
Name: proportion, dtype: float64

## Q10. Sort DataFrame by Salary

Input:
Name   Salary
Aman   30000
Raj    50000
Riya   40000

Output:
Raj
Riya
Aman

In [69]:
df = pd.DataFrame({
    'Name':['Aman','Raj','Riya'],
    'Salary':[30000,50000,40000]
})
df
print(df.sort_values(by='Salary',ascending=False)['Name'])

1     Raj
2    Riya
0    Aman
Name: Name, dtype: object

## Q11. Find Correlation

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
1.0

In [70]:
df = pd.DataFrame({
    'Math':[10,20,30,40],
    'Science':[15,25,35,45]
})
df
print(df.corr(numeric_only=True))

         Math  Science
Math      1.0      1.0
Science   1.0      1.0

## Q12. Find Covariance

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
166.67 (approx)

In [71]:
df
print(df.cov(numeric_only=True))

               Math     Science
Math     166.666667  166.666667
Science  166.666667  166.666667

## Q13. Sort by Two Columns

Input:
Sort by City and then Age

Output:
Sorted DataFrame

In [72]:
df = pd.DataFrame({
    'Name':['Sandeep','Suman','Riju','Vishesh'],
    'City':['Bhopla','Indore','Katni','Jabalpur'],
    'Age':[50,60,30,40]
})
df
df.sort_values(by=['Age'])

      Name      City  Age
2     Riju     Katni   30
3  Vishesh  Jabalpur   40
0  Sandeep    Bhopla   50
1    Suman    Indore   60

## Q14. Student Statistics

Input:
Marks = [60,70,80,90]

Output:
Mean = 75
Median = 75
Max = 90
Min = 60

In [73]:
df = pd.DataFrame({
    'Marks':[60,70,80,90]
})
df
print(df.describe())

           Marks
count   4.000000
mean   75.000000
std    12.909944
min    60.000000
25%    67.500000
50%    75.000000
75%    82.500000
max    90.000000

## Q15. Mini Practice

Create a DataFrame with:
Name, Age, Score, Height

Tasks:
1. Sort by Score (Descending)
2. Find Mean Age
3. Find Median Height
4. Show Score Frequency

In [82]:
df = pd.DataFrame({
    'Name':['Sandeep','Suman','Riju','Vishesh'],
    'Age':[50,60,30,40],
    'Score':[70,65,90,70],
    'Height':[5.9,5.2,5.5,6.5]
})
df
print(df.sort_values(by='Score', ascending=False))
print(df.Age.mean(numeric_only=True))
print(df.Height.median(numeric_only=True))
print(df.Score.value_counts())

      Name  Age  Score  Height
2     Riju   30     90     5.5
0  Sandeep   50     70     5.9
3  Vishesh   40     70     6.5
1    Suman   60     65     5.2
45.0
5.7
Score
70    2
65    1
90    1
Name: count, dtype: int64